### ISSUE TITLE
Unable to connect to Elastic with specified elastic user

### ISSUE THREAD

**Issue by skirven4** [elastic/eck-diagnostics#246]
Elastic Support Case: 01644420

Issue: I created a static secret for the elastic user per the documentation: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html. The user works as expected in Elastic and Kibana.

The issue is that because of the secret not being created, the Diagnostic script cannot login:
"If you specify the password for the elastic user through such a basic authentication secret then the secret holding the password described in Default elastic user<[https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html#k8s-default-elastic-user>](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-users-and-roles.html#k8s-default-elastic-user%3E) will not be created by the operator."

Shouldn't the Diagnostic app try to use the secret user if it's available from the deployment? Or maybe ECK should create the secret if it's not present for this reason?

**Comment by thbkrkr** [comment]
> Shouldn't the Diagnostic app try to use the secret user if it's available from the deployment? 

To be able to do that, we would need to put more knowledge about the ECK operator into the eck-diagnostics code and that is not something we want to do.

> Or maybe ECK should create the secret if it's not present for this reason?

That will not work when users want no default elastic user, see:

- https://github.com/elastic/cloud-on-k8s/issues/7719

Since ECK 2.13.0, the operator creates a dedicated user for the eck-diagnostics, independent of the elastic user. This should cover your case?

- https://github.com/elastic/cloud-on-k8s/pull/7723

**Comment by skirven4** [comment]
Aha! That makes total sense. I did search some through the code but was not sure what I was looking for. I need to upgrade the operator very soon.
Thank you!!
