### ISSUE TITLE
Azure AKS with AAD integration fails

### ISSUE THREAD

**Issue by bugie** [elastic/eck-diagnostics#61]
When trying to run the eck-diagnostics tool against our Azure AKS cluster with AAD Auth, I get the below error. Using the cluster admin kubeconfig, the tools works fine. 

`Error: failed to retrieve OpenAPI schema: no openapi getter`

**Comment by Doriangaensslen** [comment]
il get the same error but on an on premise k8s OS Ubuntu 21.10 go1.17.
`eck-diagnostics -r namespace`
`Error: failed to retrieve OpenAPI schema: no openapi getter`

I've tried Version 1.0.1 and 1.0.0 both with the same result. Verbose didnt help.

**Comment by pebrc** [comment]
Users have to install [kubelogin](https://github.com/Azure/kubelogin) and call `kubelogin convert-kubeconfig` before using `eck-diagnostics` in order to be able to use the Azure Active Directory login flow. 

There is also an [in-tree Azure auth plugin](https://github.com/kubernetes/client-go/blob/master/plugin/pkg/client/auth/azure/azure.go) that we can integrate into `eck-diagnostics` but it is important to point out that it is deprecated and will go away in Kubernetes 1.25, so that would only be temporary solution and the way forward is external credential plugins like `kubelogin`.
